version: "3.9"

services:
  # db:
  #   image: postgis/postgis:15-3.4
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB:-mydb}
  #     POSTGRES_USER: ${POSTGRES_USER:-myuser}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypass}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 20

  web:
    build: .
    restart: always
    env_file: .env
    # depends_on:
    #   db:
    #     condition: service_healthy
    volumes:
      - static_data:/vol/static
      - media_data:/vol/media
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./docker/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/var/www/static:ro
      - media_data:/var/www/media:ro
    ports:
      - "80:80"
      # (Later add 443 after TLS)
    depends_on:
      - web

volumes:
  # postgres_data:
  static_data:
  media_data:
