from django.urls import path

from . import views

urlpatterns = [
    path(
        "profiles/",
        views.AnimalProfileListAPI.as_view(),
        name="animal-profiles-list",
    ),
    path(
        "sightings/nearby/",
        views.NearbySightingsAPI.as_view(),
        name="nearby-sightings",
    ),
    path(
        "sightings/create/",
        views.CreateSightingAPI.as_view(),
        name="create-sighting",
    ),
    path(
        "sightings/select-profile/",
        views.SightingSelectProfileAPI.as_view(),
        name="sighting-select-profile",
    ),
    path(
        "emergencies/nearby/",
        views.NearbyEmergenciesAPI.as_view(),
        name="nearby-emergencies",
    ),
    path(
        "emergencies/create/",
        views.EmergencyCreateAPI.as_view(),
        name="create-emergency",
    ),
    path(
        "pets/register/",
        views.RegisterPetAPI.as_view(),
        name="register-pet",
    ),
    path(
        "pets/upload-images/",
        views.UploadImageAPI.as_view(),
        name="upload-image",
    ),
    path(
        "my-pets/",
        views.UserPetsListAPI.as_view(),
        name="user-pets-list",
    ),
    path(
        "pets/mark-as-lost/",
        views.MarkPetAsLostAPI.as_view(),
        name="mark-pet-as-lost",
    ),
    path(
        "adoptions/nearby/",
        views.NearbyAdoptionsAPI.as_view(),
        name="nearby-adoptions",
    ),
    path(
        "adoptions/my-listings/",
        views.OrganisationAdoptionsListAPI.as_view(),
        name="organisation-adoptions-list",
    ),
    path(
        "adoptions/mark-adopted/",
        views.MarkAdoptionAsAdoptedAPI.as_view(),
        name="mark-adoption-adopted",
    ),
]
